### PR TITLE
add script that creates singularity image for UWLCM with GPU support

### PR DESCRIPTION
**Pull request by trontrytel**
Thanks to great help from @mwarusz I'm finally done with the singularity image for UWLCM. 

It is based on ubuntu 18.04 and cuda 10.0. Hope this helps some future users. 

In the pull I just add the script that creates it and instructions how to do it. Let me know if you want the image too. Or if you want to try to create it yourself and test things. I'm assuming that both the libraries and UWLCM may still change. Therefore they are not part of the image but have to be installed locally later inside the image. If thats not the case they could be added to it when the image is build.

A side note 1: I also tried with an image based on ubuntu 16.04 and cuda 8.0 but I got some errors when compiling the moist thermal in UWLCM. I'm leaving it for now since it works with the newer versions. But in case you want to run it on a machine with older cuda version its probably not far from working too. Let me know if you want that script too.

A side note 2: It takes extremely long time to compile UWLCM. Maybe it would be useful to suggest a minimal/default set of options to compile. And ignore the others.

### CODE REVIEW

**Comment by trontrytel** [comment]
Also thank are due to @djarecka who helped me get started with Singularity :)   @djarecka - here is the final solution...

**Comment by pdziekan** [comment]
I've tested building and using the image and it works! Thanks for the contribution.

I have two small suggestions:

1. Move singularity files (script and readme) to a separate folder.

2. In singularity readme specify install location with
`cmake -DCMAKE_INSTALL_PREFIX=/local_folder/`
instead of
`make install DESTDIR=/local_folder/`.
Using INSTALL_PREFIX has the advantage that it gives correct rpath in the python bindings of libcloudph++

**Comment by trontrytel** [comment]
Done. @pdziekan , since we are looking at the installation stuff. Would it make sense to put both libmpdata and libcloud config files in the same place? 

Right now:
 ```Dlibmpdata++_DIR=/local_folder/usr/local/share/libmpdata++``` but  
 ```Dlibcloudph++_DIR=/local_folder/usr/local/lib/cmake/libcloudph++```. 

The symmetry and the overall order in the world would improve.

**Comment by trontrytel** [comment]
> I've tested building and using the image and it works! 

I must say I almost don't believe that it worked :)

**Comment by pdziekan** [comment]
libcloud PR changing install location of cmake config to share/:
 https://github.com/igfuw/libcloudphxx/pull/377

**Pull request merged**
