### PR TITLE
Blk 1m opts

### PR DESCRIPTION
**Pull request by trontrytel**
- add blk_1m autoconversion parameters as user options to UWLCM
- remove some white spaces

### CODE REVIEW

**Comment by trontrytel** [comment]
@pdziekan - Do you understand why the ```api_test_iles_diff``` is failing for this pull request? Do I need to update the reference files?

**Comment by pdziekan** [comment]
@trontrytel yes, r_eps default is changed from 1e-6 to 2e-5 and the reference files need to be updated.
BTW is there need to change default r_eps? Maybe it would be better to keep it as it was?

**Comment by trontrytel** [comment]
> @trontrytel yes, r_eps default is changed from 1e-6 to 2e-5 and the reference files need to be updated.
> BTW is there need to change default r_eps? Maybe it would be better to keep it as it was?

I'll change the default value back to the default value and re-run the tests

**Comment by trontrytel** [comment]
> @trontrytel yes, r_eps default is changed from 1e-6 to 2e-5 and the reference files need to be updated.
> BTW is there need to change default r_eps? Maybe it would be better to keep it as it was?

I think I'm setting the value to be the default value from libcloudph:
https://github.com/igfuw/UWLCM/blob/d1b54db1879b6f2b35fc55c42f06266426dcb27e/src/opts/opts_blk_1m.hpp#L36

The default value in libcloudph is 2e-5:
https://github.com/igfuw/libcloudphxx/blob/b4bd593eaf64f36fa6a8265d409102b98e213262/include/libcloudph%2B%2B/blk_1m/options.hpp#L27

and it was like this for a long time. I'm not sure where I should change it to 1e-6? And Why do you have that as the default?

**Comment by pdziekan** [comment]
I can't remember why r_eps in UWLCM is set to 1e-6, but I suppose there is some reason :)

Two ways to proceed with the PR:
1. Set the default r_eps in UWLCM to 1e-6 as it was.
2. Change default r_eps in UWLCM to 2e-5, the default of libcloudphxx. Update reference files for api tests. See if moist_thermal test passes.

**Pull request merged**
